name: dailyhoroscopes
description: It is a flutter application where you can follow daily horoscope information.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #State Management
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  #Database
  hive_flutter: ^1.1.0

  #Network
  vexana: ^3.0.1
  connectivity_plus: ^2.3.6

  #Localization
  easy_localization: ^3.0.1

  #Navigation
  go_router: ^4.2.2

  #JSON
  json_annotation: ^4.6.0

  #Core
  equatable: ^2.0.3

  #UI Utitilities
  flutter_svg: ^1.1.1+1
  animated_text_kit: ^4.2.2
  kartal: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mobx_codegen: ^2.0.7
  hive_generator: ^1.1.3
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "asset/image/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/svg/
    - asset/lang/
